apiVersion: v1
kind: Secret
metadata:
  name: base-secret
  namespace: flux-system
type: Opaque
data:
  username: eHVwZW5ndG9ueQ==
  password: MTIzNEFCY2Q=

---

apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: spring-petclinic-config-repo
  namespace: flux-system
spec:
  interval: 2m0s
  url: https://gitee.com/xupengtony/spring-petclinic-config
  ref:
    branch: master
  secretRef:
    name: base-secret

---

apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: spring-petclinic-config
  namespace: flux-system
spec:
  interval: 3m0s
  sourceRef:
    kind: GitRepository
    name: spring-petclinic-config-repo
    namespace: flux-system
  prune: true
  wait: true
  timeout: 5m0s
